# Generated by Django 3.2 on 2021-05-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('StartDate', models.DateTimeField(max_length=50)),
                ('EndDate', models.DateTimeField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
    ]
