# Generated by Django 3.0.5 on 2021-05-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condidat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('NameCondidat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Degrees', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameSpecialite', models.CharField(max_length=30)),
                ('NumberCv', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='offre',
            name='EndDate',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offre',
            name='StartDate',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
