# Generated by Django 3.0.5 on 2021-06-21 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20210525_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Names', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=1000000)),
                ('Names', models.CharField(max_length=100)),
                ('Degrees', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Condidat',
        ),
        migrations.RenameField(
            model_name='specialite',
            old_name='NameSpecialite',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='cv',
            name='Category',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='Content',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='Names',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offre',
            name='Description',
            field=models.CharField(max_length=100000),
        ),
    ]
