# Generated by Django 3.0.5 on 2021-06-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20210621_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='Content',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='Names',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='Description',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
