# Generated by Django 3.0.5 on 2021-07-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20210621_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Names', models.CharField(max_length=100)),
                ('cv', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='offre',
            name='Description',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
    ]
