# Generated by Django 3.0.5 on 2021-07-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0005_auto_20210704_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cand',
            old_name='Names',
            new_name='nom',
        ),
    ]
